// src/main.jsx
import React from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";

import Login from "./pages/auth/Login.jsx";
import Register from "./pages/auth/Register.jsx";

/* Layout */
import AdminLayout from "./layouts/AdminLayout.jsx";
import UserLayout from "./layouts/Userlayout.jsx"; 

/* Admin Pages */
import Dashboard from "./pages/admin/Dashboard";
import Venuemaster from "./pages/admin/venue/Venuemaster.jsx";
import Eventmaster from "./pages/admin/Event/Eventmaster.jsx";
import Sports from "./pages/admin/sports/createsports.jsx";
import Player from "./pages/admin/Players/PlayerList.jsx";
import Users from "./pages/admin/user_roles/user_roles.jsx";
import Team from "./pages/admin/Teams/TeamList.jsx";
import Tournament from "./pages/admin/Tournaments/TournamentList.jsx";


// END-USER PAGES
import UserDashboard from "./pages/End_user/Dashboard.jsx";
import EventListingPage from "./pages/End_user/EventListingPage.jsx";
import EventDetailsPage from "./pages/End_user/EventDetailsPage.jsx";
import FixtureList from "./pages/End_user/Fixturelist.jsx";
import LiveMatchPage from "./pages/End_user/LiveMatchPage.jsx";
import ScorecardPage from "./pages/End_user/ScorecardPage.jsx";
import PlayerListingPage from './pages/End_user/PlayerListingPage.jsx';
import PlayerList from "./pages/End_user/Players.jsx";
import TeamList from "./pages/End_user/TeamList.jsx";
import PlayerProfilePage from './pages/End_user/PlayerProfilePage.jsx';
import StandingsPage from './pages/End_user/Standings.jsx';
import UserTournamentDetail from "./pages/End_user/UserTournamentDetail.jsx";

import "./index.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <BrowserRouter basename="/SPORTS-TOURNAMENT-SYSTEM">
    <Routes>
      {/* PUBLIC */}
      <Route path="/" element={<Login />} />
      <Route path="/register" element={<Register />} />

      {/* END-USER ROUTES (Base Path is now /user) */}
      

<Route path="/user" element={<UserLayout />}>
    
    {/* 1. Base URL Redirect: If user navigates to just /user, redirect them to the listing page. */}
    <Route path="" element={<Navigate to="event_listing" replace />} />
    <Route path="tournament/:id" element={<UserTournamentDetail />} />
    <Route path="dashboard" element={<UserDashboard />} />
    {/* 2. Event Listing Page (FIXED: Path is now RELATIVE: "event_listing") */}
    {/* Full URL: /user/event_listing. Matches your sidebar. */}
    <Route path="event_listing" element={<EventListingPage />} /> 

    {/* 3. Event Details Page (Handles /user/12345) */}
    {/* This route handles the absolute link generated by the event card. */}
    <Route path=":id" element={<EventDetailsPage />} /> 

    {/* 4. Dynamic Match Pages (These are fine) */}
   <Route path=":eventId/live/:matchId" element={<LiveMatchPage />} />
    <Route path=":eventId/scorecard/:matchId" element={<ScorecardPage />} />

      {/* Fixtures */}
            <Route path="fixtures" element={<FixtureList />} />
            <Route path="fixtures/:tournamentId?" element={<FixtureList />} />
    
    {/* 5. General Pages (Sidebar links) */}
    <Route path="player_stats" element={<PlayerListingPage />} />
    <Route path="players/:playerId" element={<PlayerProfilePage />} />
    <Route path="/user/standings" element={<StandingsPage />} />
    {/* Add your other sidebar pages here: */}
    {/* <Route path="fixtures" element={...} /> */}

     {/* Teams */}
            <Route path="teams" element={<TeamList />} />
             {/* Players */}
        <Route path="players" element={<PlayerList />} />
  
</Route>



      {/* ADMIN (AdminLayout wraps all admin routes) */}
      <Route path="/admin" element={<AdminLayout />}>
        <Route path="dashboard" element={<Dashboard />} />
        <Route path="event" element={<Eventmaster />} />
        <Route path="venue" element={<Venuemaster />} />
        <Route path="sports" element={<Sports />} />
        <Route path="player" element={<Player />} />
        <Route path="users" element={<Users />} />
        <Route path="team" element={<Team />} />
        <Route path="tournament" element={<Tournament />} />
      </Route>
    </Routes>
  </BrowserRouter>
);